version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sensors
      POSTGRES_USER: sensors
      POSTGRES_PASSWORD: sensors
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sensors -d sensors"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: sensors
      POSTGRES_USER: sensors
      POSTGRES_PASSWORD: sensors
      POSTGRES_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["/app/entrypoint.sh"]

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "3000:3000"

volumes:
  pgdata:
