# Generated by Django 4.2.24 on 2025-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_name'),
        ),
    ]
