# Generated by Django 4.2.24 on 2025-09-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensor_uniq_owner_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor',
            name='uniq_owner_name',
        ),
    ]
