# Generated by Django 4.2.24 on 2025-09-29 14:52

from django.db import migrations, models


def dedupe_sensors(apps, schema_editor):
    Sensor = apps.get_model("sensors", "Sensor")
    seen = set()

    for sensor in Sensor.objects.all().order_by("id"):
        key = (sensor.owner_id, sensor.name)
        if key in seen:
            sensor.delete()  # ta bort dubblett
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_remove_sensor_uniq_owner_name"),
    ]

    operations = [
        migrations.RunPython(dedupe_sensors, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="sensor",
            constraint=models.UniqueConstraint(
                fields=["owner", "name"], name="uniq_owner_name"
            ),
        ),
    ]

